_security_logout:
    resource: security.route_loader.logout
    type: service

admin:
    path: /admin
    controller: App\Controller\AdminController::index

user:
    path: /user
    controller: App\Controller\UserController::index

